[package]
name = "geph5-ip-to-asn"
edition = "2024"
version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.98"
moka = { version = "0.12.7", features = ["future"] }
flate2 = "1.0.33"
reqwest = { version = "0.12.5", default-features = false, features = [
  "rustls-tls",
] }