[package]
name = "sillad-meeklike"
edition = "2021"
version = "0.1.0"
description = "A meek-like HTTP polling protocol within the sillad framework"
repository.workspace = true
license.workspace = true

[dependencies]
async-compat = "0.2.4"
async-task = "4.7.1"
async-trait = "0.1.86"
async-channel = "1.9.0"
blake3 = "1.5.1"
bytes = "1.5.0"
chacha20poly1305 = "0.10.1"
dashmap = "5.5.3"
futures-util = { version = "0.3.30", features = ["io"] }
futures-lite = "2.6.0"
http-body-util = "0.1.2"
hyper = { version = "1.6.0", features = ["http1", "client", "server"] }
hyper-util = { version = "0.1.13", features = ["tokio"] }
rand = "0.8.5"
smolscale = "0.4.11"
smol-timeout2 = "0.6.1"
pin-project = "1.1.5"
bipe = "0.2.8"
sillad = { version = "0.2", path = "../sillad" }
tracing = "0.1.41"
