[package]
name = "nanorpc-sillad"
version = "0.1.2"
edition = "2021"
description = "nanorpc transport over sillad pipes"
repository.workspace = true
license.workspace = true

[dependencies]
sillad = { version = "0.2", path = "../sillad" }
async-trait = "0.1.88"
nanorpc = "0.1.13"
serde_json = "1.0.141"
thiserror = "1.0.69"
anyhow = "1.0.98"
futures-util = { version = "0.3.31", features = ["io"] }
async-executor = "1.13.2"
